name: bitcoin
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bottleneck=1.2.1=py36h035aef0_1
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.3.9=py36_0
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py36_1000
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gast=0.2.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=hf63aee3_1001
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.4=243
  - ipykernel=5.1.1=py36h24bf2e0_0
  - ipython=7.5.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.2.4=py_3
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.8.0=h8b12597_0
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - markupsafe=1.1.1=py36h14c3975_0
  - mistune=0.8.4=py36h14c3975_1000
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - mock=3.0.5=py36_0
  - mpi4py=2.0.0=py36_2
  - mpich2=1.4.1p1=0
  - nb_conda=2.2.1=py36_2
  - nb_conda_kernels=2.2.2=py36_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=he6710b0_1
  - notebook=5.7.8=py36_1
  - numpy=1.16.4=py36h7e9f1db_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - openssl=1.1.1b=h14c3975_1
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.4.0=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.1.1=py36_0
  - prometheus_client=0.7.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.4.2=py_0
  - pyqt=5.9.2=py36hcca6a23_0
  - pyrsistent=0.15.2=py36h516909a_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py_0
  - python-snappy=0.5.4=py36hee44bf9_0
  - qt=5.9.7=h52cfd70_2
  - qtconsole=4.5.1=py_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - snappy=1.1.7=he1b5a44_1002
  - sqlite=3.28.0=h7b6447c_0
  - tensorboard=1.13.1=py36_0
  - tensorflow=1.13.1=py36_0
  - tensorflow-estimator=1.13.0=py_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.2=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - webencodings=0.5.1=py_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.4.2=py36_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=hf484d3e_1000
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.7.1
    - alembic==1.0.10
    - astor==0.8.0
    - atomicwrites==1.3.0
    - click==7.0
    - cliff==2.14.1
    - cmd2==0.9.12
    - colorama==0.4.1
    - empyrical==0.5.0
    - future==0.17.1
    - glob2==0.7
    - grpcio==1.21.1
    - gym==0.12.5
    - h5py==2.9.0
    - importlib-metadata==0.18
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - lxml==4.3.4
    - mako==1.0.12
    - markdown==3.1.1
    - more-itertools==7.0.0
    - okex==0.1.6
    - opencv-python==4.1.0.25
    - optuna==0.12.0
    - packaging==19.0
    - pandas==0.24.2
    - pandas-datareader==0.7.0
    - patsy==0.5.1
    - pluggy==0.12.0
    - prettytable==0.7.2
    - protobuf==3.8.0
    - py==1.8.0
    - pyglet==1.3.2
    - pyperclip==1.7.0
    - pytest==4.6.3
    - pytest-mock==1.10.4
    - python-editor==1.0.4
    - pyyaml==5.1.1
    - pyzmq==18.0.1
    - scikit-learn==0.21.2
    - scipy==1.3.0
    - seaborn==0.9.0
    - sqlalchemy==1.3.4
    - stable-baselines==2.5.1
    - statsmodels==0.10.0rc2
    - stevedore==1.30.1
    - ta==0.4.5
    - tensorflow-gpu==1.13.1
    - termcolor==1.1.0
    - tqdm==4.32.1
    - typing==3.6.6
    - wcwidth==0.1.7
    - wrapt==1.11.1
    - xgboost==0.90
    - zipp==0.5.1
prefix: /home/thorad/.conda/envs/bitcoin

